import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nvbr from "@/components/Nvbr";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "palm edu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={cn(
            'min-h-screen font- antialiased grainy bg-emerald-200',
            inter.className
          )}>
       
        { children}</body>
    </html>
  );
}
